export const FETCH_MEMOS_REQUEST    = 'FETCH_MEMOS_REQUEST';
export const FETCH_MEMOS_SUCCESS    = 'FETCH_MEMOS_SUCCESS';
export const FETCH_MEMOS_FAILURE    = 'FETCH_MEMOS_FAILURE';

export const REMOVE_MEMO_CONFIRM    = 'REMOVE_MEMO_CONFIRM';
export const REMOVE_MEMO_CANCEL     = 'REMOVE_MEMO_CANCEL';
export const REMOVE_MEMO_REQUEST    = 'REMOVE_MEMO_REQUEST';
export const REMOVE_MEMO_SUCCESS    = 'REMOVE_MEMO_SUCCESS';
export const REMOVE_MEMO_FAILURE    = 'REMOVE_MEMO_FAILURE';

export const EDIT_MEMO_FIELD_CHANGE = 'EDIT_MEMO_FIELD_CHANGE';
export const EDIT_MEMO_EXISTING     = 'EDIT_MEMO_EXISTING';
export const EDIT_MEMO_CANCEL       = 'EDIT_MEMO_CANCEL';
export const EDIT_MEMO_REQUEST      = 'EDIT_MEMO_REQUEST';
export const EDIT_MEMO_SUCCESS      = 'EDIT_MEMO_SUCCESS';
export const EDIT_MEMO_FAILURE      = 'EDIT_MEMO_FAILURE';

export const DESCRIPTION_MEMO_GET = 'DESCRIPTION_MEMO_GET';